### ISSUE TITLE
[CX] Make CX receipt table transmission to destination shard reliable

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony#1396]
## Summary

After including the first half (withdraw-only) of a cross-shard transaction (CX) in a block, the source leader sends the block header to the beacon committee for inclusion in the beacon chain (“crosslink”) and the table of all CX receipts in that block to the destination committee for crediting.  If the CX receipt table gets lost on its way to destination shard without any recovery logic, the destination accounts never get credited.

## Impact

Lost CX receipt table, e.g. due to flakey network conditions, will:

* Cause a CX to remain unfinished indefinitely, having withdrawn fund from source account without crediting the destination account (“lost fund”).

**Comment by LeoHChen** [comment]
@rlan35 , please triage, if it is still the issue for cross shard token transfer.

**Comment by LeoHChen** [comment]
After discussion with @rlan35 , this issue is not a problem anymore as we are sending the cx receipt to destination shard directly now.  However, the message may still lose, we are using a mitigation right now to find all the pending receipts in API. https://github.com/harmony-one/harmony/issues/2085

**Comment by LeoHChen** [comment]
close it for now.
