### ISSUE TITLE
Another node crash in Pangaea

### ISSUE THREAD

**Issue by xChickens** [harmony-one/harmony#1400]
2019/08/22 00:05:43 Stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8796b9]

goroutine 13 [running]:
github.com/harmony-one/harmony/core/types.(*Block).Root(...)
        /data/harmony-main/core/types/block.go:379
github.com/harmony-one/harmony/core.(*BlockChain).insertChain(0xc00048e000, 0xc0033d3d28, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/harmony-main/core/blockchain.go:1234 +0x1139
github.com/harmony-one/harmony/core.(*BlockChain).InsertChain(0xc00048e000, 0xc0033d3d28, 0x1, 0x1, 0x42, 0xc00df38540, 0xc0033d3d90)
        /data/harmony-main/core/blockchain.go:1101 +0x67
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).updateBlockAndStatus(0xc0020c2930, 0xc014a6e480, 0xc00048e000, 0xc0004deac0, 0x6c4f81c7cc7e1ac1)
        /data/harmony-main/api/service/syncing/syncing.go:535 +0x186
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).generateNewState(0xc0020c2930, 0xc00048e000, 0xc0004deac0)
        /data/harmony-main/api/service/syncing/syncing.go:564 +0x12c
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).ProcessStateSync(0xc0020c2930, 0xc00febfe40, 0x20, 0x20, 0x6c4f81c7000001d2, 0xc00048e000, 0xc0004deac0)
        /data/harmony-main/api/service/syncing/syncing.go:623 +0xb0
github.com/harmony-one/harmony/api/service/syncing.(*StateSync).SyncLoop(0xc0020c2930, 0xc00048e000, 0xc0004deac0, 0x1)
        /data/harmony-main/api/service/syncing/syncing.go:737 +0xba
github.com/harmony-one/harmony/node.(*Node).DoSyncing(0xc000537000, 0xc00048e000, 0xc0004deac0, 0xc000f84050, 0x1)
        /data/harmony-main/node/node_syncing.go:140 +0x19e
created by github.com/harmony-one/harmony/node.(*Node).SupportSyncing

**Comment by flicker-harmony** [comment]
After running localnet for may hours - wasn't able to replicate pangea crush, I'll try to run it with more than 100 nodes
But what I've noticed from analyzing the code
Is that forking mechanism is still only partially implemented
(there is a TODO for that)
Maybe error has smth to do with syncing after forks
Also errors looks strange - basically it happens when parent block fetched but it's nil, fails to take parent.Root() by nil pointer
<img width="1007" alt="Screenshot 2019-08-23 at 20 43 08" src="https://user-images.githubusercontent.com/52401354/63613486-92a74b80-c5e9-11e9-83fc-6977589c8f65.png">
And error logging showed that
github.com/harmony-one/harmony/core.(BlockChain).insertChain(0xc00048e000, 0xc0033d3d28, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/data/harmony-main/core/blockchain.go:1234 +0x1139
github.com/harmony-one/harmony/core.(BlockChain).InsertChain(0xc00048e000, 0xc0033d3d28, 0x1, 0x1, 0x42, 0xc00df38540, 0xc0033d3d90)
It should insert equal chain into insertChain as in InsertChain - both accept "chain types.Blocks" and chain isn't changed in InsertChain - passed to insertChain right at the start
But pointers as args in methods are different
I'm running my localnet and it inserts only 1 block, but maybe because there is no resyncing and forks
