### ISSUE TITLE
Node runner education and certificate program

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#1761]
We should design a node operator training and certificate program to help new stakers become a valid node operator.

The training program shall include, but not limited to,

1) cloud server management, basic cloud provider training, key, ssh, terminal
2) basic Linux system administration, monitoring, triage, upgrade
3) harmony node running guidance, key management
4) harmony node upgrade training, build, monitoring
5) node runner has to run a node on testnet for 1 week, successfully upgrade the node and got the certificate

**Comment by sophoah** [comment]
Hey Leo, what do you think if P-OPS come up with a list of training documentation/guide and maybe as well a MCQ to test on suggested topic 1, 2 and 3?

**Comment by LeoHChen** [comment]
feel free to comment on the ticket for some idea as well.

**Comment by JB273** [comment]
Node operator guide/training can be done/monitored by P-OPS:

1. Of course depends on cloud provider, from Pangaea project we have multiple options to choose 
from, but also be aware of using password manager (Keepass) and storing received key(s) on local system and make cloud backup.
2. Make operator aware of different harmony tools available (TUI, Watchdog, hmycli), but also using "htop" instead of basic"top", but also secure the node, like not running SSH on port 22, create MFA  for login to the node, open up only necessary ports etc. etc.
3. Running a node for a minimum period in Pangaea and at least do an upgrade once on his/her own, run needed management task or automate these. Able to perform basic tasks with hmycli like getting balance, doing transfer (TX and CX) and what features may come...
4. Upgrading and/or building up the node could be like an "exam" task, need to upgrade the node within 24 hours and provide proof to the Pangaea team.
5. Pangaea P-OPS will send message to contact in DEV team about the exam results of the candidate!

Is this something you can work with for starters?

**Comment by LeoHChen** [comment]
looks very good to me in technical details . Let's work with Gizem to
develop the content and find a delivery format.
-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by LeoHChen** [comment]
not needed anymore, validator dao can handle it.
