### ISSUE TITLE
[Feature]add insufficient funds error to RPC

### ISSUE THREAD

**Issue by neeboo** [harmony-one/harmony#1858]
# Problem/limitation At Hand

When sending a transaction via RPC service, we should return error of insufficient funds if the balance have not enough token to cover the `gasLimit*gasPrice+value`

**Which component?**

- [ ] consensus
- [ ] deploy script
- [ ] wallet
- [ ] explorer
- [ ] node script
- [ ] test automation
- [ ] demo app
- [x] RPC
- [ ] others ...

# Proposed Solution

JSON-RPC should return error like:
```bash
{
  "id":1,
  "jsonrpc": "2.0",
  "error": {
    "code": -32000,
    "message": "insufficient funds for gasLimit * gasPrice + value"
  }
}
```

# Alternatives Considered

# Additional Context

**Comment by fxfactorial** [comment]
I don't think this is the right approach because the actual gas cost will only be known when the EVM rejects the txn or not which will happen well after the submission of the RPC. 

In addition, it would be a needless computation for the blockchain receiving RPC node to do when the majority of txn won't be processed.
