### ISSUE TITLE
able to stake more than I should, might be link to issue 2009

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2010]
**Describe the bug**
I was able to delegate more than I should

**To Reproduce**
So following up the previous setup, my wallet had 
root@vmi317161:~/hmy-devnet# ./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph                                          [
  {
    "shard": 0,
    "amount": 7437.999939252
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

so i decided to claim my reward which went well and 
root@vmi317161:~/hmy-devnet# ./hmy --node="https://api.s0.pga.hmny.io" staking collect-rewards --delegator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --chain-id devnet
{"transaction-receipt":"0x257d27731b85047788b075698ee64e3ce84ab4256946147ef1d16037a1a879cb"}

and now have 14k
root@vmi317161:~/hmy-devnet# ./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph
[
  {
    "shard": 0,
    "amount": 14006.93406856
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

then decided to stake the full wallet amount that i had : 
root@vmi317161:~/hmy-devnet# ./hmy --node="https://api.s0.pga.hmny.io" staking delegate --delegator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --validator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --amount 14006 --chain-id devnet
{"transaction-receipt":"0x9f65827dc4155e67fa0d5675665c1914ec4cbddc2a892298228a75f0122e2ac6"}

and everything went well again and the staking explorer confirmed i have now 21,493

and for fun, retried a few time later if i could restake again the 14k:
./hmy--node="https://api.s0.pga.hmny.io" staking delegate --delegator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --validator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --amount 14006 --chain-id devnet
{"transaction-receipt":"0x448ea36e78d65392bd5c1cd7a9f5b66416112382d09d9756863914fc0f3b1f46"}

and this time no issue, i got the staking error:
    {
      "directive-kind": "Delegate",
      "error-message": "insufficient balance to stake",
      "time-at-rejection": 1576080035,
      "tx-hash-id": "0x448ea36e78d65392bd5c1cd7a9f5b66416112382d09d9756863914fc0f3b1f46"
    }

**Expected behavior**
Should be able to add stake as a delegator if the wallet has part of the fund being blocked.

**Screenshots**
here is the full staking error that should have included the staking of 14k, which has only the second attempt error of 14k staking
root@vmi317161:~/hmy-devnet# ./hmy failures staking --node="https://api.s0.pga.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": [
    {
      "directive-kind": "CreateValidator",
      "error-message": "insufficient balance to pay for gas",
      "time-at-rejection": 1576049281,
      "tx-hash-id": "0xe02045667c208f860a62008dce2266e3a314b90b1c58db54245d2e1e1a274e67"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "insufficient balance to stake",
      "time-at-rejection": 1576052305,
      "tx-hash-id": "0x32ece961a3ee9fb9842bb3d56d9e1b6d9f01ff5d2254b547d2b6373199f22b55"
    },
    {
      "directive-kind": "CreateValidator",
      "error-message": "insufficient balance to pay for gas",
      "time-at-rejection": 1576062960,
      "tx-hash-id": "0xc881bb739d8041066569c585bb10bd200ed673aa437c3524fae2a88ac1b754af"
    },
    {
      "directive-kind": "CreateValidator",
      "error-message": "insufficient balance to pay for gas",
      "time-at-rejection": 1576063726,
      "tx-hash-id": "0xc881bb739d8041066569c585bb10bd200ed673aa437c3524fae2a88ac1b754af"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "total delegation can not be bigger than max_total_delegation",
      "time-at-rejection": 1576065393,
      "tx-hash-id": "0x4bf8c7ac8a9e332cd888e98b6d18408ef7fe076091ba38e8510735c6ea38fcba"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "total delegation can not be bigger than max_total_delegation",
      "time-at-rejection": 1576065704,
      "tx-hash-id": "0x5b68d98279a52d67caa933f40e2fcb4540e787c71e73a52ea03288f31aa4ee43"
    },
    {
      "directive-kind": "CreateValidator",
      "error-message": "staking validator already exists",
      "time-at-rejection": 1576072069,
      "tx-hash-id": "0x14f9312d46449a8960368c4522d798783929169fa3a4162f64ec4f48d381739d"
    },
    {
      "directive-kind": "Delegate",
      "error-message": "insufficient balance to stake",
      "time-at-rejection": 1576080035,
      "tx-hash-id": "0x448ea36e78d65392bd5c1cd7a9f5b66416112382d09d9756863914fc0f3b1f46"
    }
  ]
}
**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by fxfactorial** [comment]
@sophoah I checked your balance now, 

./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --node="https://api.s0.pga.hmny.io"

And the balance is indeed gone, so can you help me understand where exactly the mistake you think is? I mean, perhaps you didn't wait in between the collectreward and then delegate again?

**Comment by mindstyle85** [comment]
no, basically he collected rewards (around 7k), so his total balance on shard 1 grew to 14k (his original 7k or so staked plus rewards seen on his balance output). But when he staked 14k (which he shouldnt since 7k and something got staked in the original create validator command), his shard 0 balance just grew to 14k, like it added 7k out of thin air @fxfactorial

**Comment by rlan35** [comment]
So his balance was this 14k before this 14k is staked,

 ===================
root@vmi317161:~/hmy-devnet# ./hmy balances one15knq45tf5psjze6q65dpm4lumqhm8jny997mph
[
{
"shard": 0,
"amount": 14006.93406856
},
{
"shard": 1,
"amount": 0.0000
}
]
===================

And he tried to stake the 14k, which went well:

======================
root@vmi317161:~/hmy-devnet# ./hmy --node="https://api.s0.pga.hmny.io" staking delegate --delegator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --validator-addr one15knq45tf5psjze6q65dpm4lumqhm8jny997mph --amount 14006 --chain-id devnet
{"transaction-receipt":"0x9f65827dc4155e67fa0d5675665c1914ec4cbddc2a892298228a75f0122e2ac6"}

and everything went well again and the staking explorer confirmed i have now 21,493
=======================

Now his balance should be close to 0, which as of now is close to 0:

[
  {
    "shard": 0,
    "amount": 0.934044016
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

His further attempt to stake 14k failed because he doesn't have enough balance to stake. These are all expected.

@mindstyle85 where is the part that token out of thin air is created? How much was the initial balance of the account? 7k? 14k?   then 7k was staked?    

One explanation is he earned 7k rewards really fast and that's why the balance grows to 21,493.

If you see the current rewards:
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "validator_address": "one15knq45tf5psjze6q65dpm4lumqhm8jny997mph",
            "delegator_address": "one15knq45tf5psjze6q65dpm4lumqhm8jny997mph",
            "amount": 21493000000000000000000,
            "reward": 29020494190920263285994,
            "Undelegations": []
        }
    ]
}
it's a lot.

**Comment by mindstyle85** [comment]
he started with 7k, got 7k of extra rewards at that time (i think, @sophoah will verify), and he saw 14k balance on his shard 0 (7k was staked in his validator connected to this account and 7k rewards). Why was he able to stake 14k, if 7k was already staked? The shard 0 balance does show his staked amount too right? 

And if current rewards are 21k (total), then its impossible he was able to stake so much so quickly, imo. I might be missing something..

**Comment by sophoah** [comment]
@rlan35 i think the thin air part is on issue 2009: those 7k before the reward claim. In that issue i was just able to add on into my stake using the 7k that came from no where technically.

**Comment by mindstyle85** [comment]
@rlan35 im guessing if a validator is created, the tokens it delegates with it should not be visible in the shard 0 balance anymore? because they are still visible there (so im guessing they are reusable too, in this case the whole 9999, although only 4999 should be available):

**VALIDATOR CREATION (wallet has 10k tokens at the start)**
./hmy --node="https://api.s0.pga.hmny.io" staking create-validator --validator-addr one1vf4hz9ah0r6g4xupl69348f5mupevqtu3mrnjn --name mind2 --identity mind2 --website mind2@harmony.one --security-contact mamapangaea2 --details "pink pony node runners v 2.0" --rate 0.1 --max-rate 0.9 --max-change-rate 0.05 --min-self-delegation 1 --max-total-delegation 0 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 5000 --chain-id devnet
Enter the bls passphrase:
{"transaction-receipt":"0xb36424331f4b197b0d02a78a2c0f6c26cd284abb565c169ba35cde25f3dcd27e"}

**CHECKING BALANCES AFTER SUCCESSFULL COMMAND (30min later)**
 ./hmy balances --node="https://api.s0.pga.hmny.i" one1vf4hz9ah0r6g4xupl69348f5mupevqtu3mrnjn 
[
  {
    "shard": 0,
    "amount": 9999.999959436
  },
  {
    "shard": 1,
    "amount": 0.0000
  }
]

**DOUBLE CHECKING THE VALIDATOR TX HASH WAS SUCCESS**
./hmy blockchain transaction-receipt 0xb36424331f4b197b0d02a78a2c0f6c26cd284abb565c169ba35cde25f3dcd27e --node="https://api.s0.pga.hmny.io" 
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x9b95c759ae7aebcf9bc30a615c26825988a7d3c026932a56a911b1c6b961a55c",
    "blockNumber": "0x452f",
    "contractAddress": null,
    "cumulativeGasUsed": "0x9e74",
    "gasUsed": "0x9e74",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "sender": "one1vf4hz9ah0r6g4xupl69348f5mupevqtu3mrnjn",
    "status": "0x1",
    "transactionHash": "0xb36424331f4b197b0d02a78a2c0f6c26cd284abb565c169ba35cde25f3dcd27e",
    "transactionIndex": "0x0",
    "type": 0
  }
}

**Comment by sophoah** [comment]
@rlan35 i understand from @mindstyle85 you managed to reproduce issue https://github.com/harmony-one/harmony/issues/2009, i believe that issue is just a continuation of the previous, if you ok after looking at that one, we can maybe close it
