### ISSUE TITLE
node didnt get accepted into quorum

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2311]
So with the new OSTN network, i created a validator with self-delegated amount 10.

There are currently >5,6k validators on OSTN (most of them are inactive bubz validators with 10 ONE stake). Since i had 10 too, did i miss getting in the quorum because my validator was created after all these bubz? (i didnt bingo and was in sync)

When i sent in another 1000 ONEs i started bingoing finally.

**Comment by sophoah** [comment]
Note that those bubz was marked as inactive and the number of validator node was around 39 at that time, so with 320 seat available, @mindstyle85 should have been accepted in the quorum. 
During that observation, his validator wasn't in the ```hmy blockchain validator all-active``` so i am suspecting a bug here in the quorum or detection of an active/inactive node.

Also node that during that same time, @mindstyle85 validator information show the active flag as true

**Comment by BrunoMarshall** [comment]
Confirmed, I added 1 validators with 10 stake and did not get bingos, only after delegate 307 ones.

**Comment by rlan35** [comment]
Note that in OSTN there is only 100 external seat available. Not 320. So that may be causing the confusion. Can anyway reproduce this in the latest OSTN?

**Comment by rlan35** [comment]
@fxfactorial  is this potentially a issue on epos election?

**Comment by sophoah** [comment]
@rlan35 since the issues was opened, the election process improved a lot. the criteria selection is now more stringent and inactive validator are being kick-out. I am not sure we can fix this issue of fake validator in the network (ie not signing). We would need to detect before hand if they are signing or if their node is online at least. All those fake validator was a spam script with no running node that were not kickout. Now with the 66% of active signature, fake validator are kick out from committee. I think we can close that issue. @mindstyle85 what do you think?

**Comment by mindstyle85** [comment]
i can but would like @fxfactorial to first check if this could still happen if we spammed lots of bubz validators or not? if not you  can close it or i will as soon as i see a reply
