### ISSUE TITLE
no staking reward in version 5599 and BLS in non shard 0

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2312]
**Describe the bug**
Since version 5599 in the new OSTN network, staking reward are no longer working for non shard 0 nodes

**To Reproduce**
Create validator and make sure the validator node has BINGOs

**Expected behavior**
After getting BINGO on our validator nodes, we should earn reward (see reward incrementing via cli or staking explorer. However reward doesn't increase.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - harmony ```Harmony (C) 2020. harmony, version v5599-master-20191208.0-222-g5681bd04 (deploy@ 2020-02-26T13:40:05+0100)```
- hmy ```Harmony (C) 2020. hmy, version v288-b6537bf (deploy@harmony.one 2020-02-26T13:40:26+0100)```

**Additional context**

**Comment by mindstyle85** [comment]
i can confirm this, i am on shard 2 and also no rewards, while JB is on s0 and has rewards

**Comment by BrunoMarshall** [comment]
I confirm that this issue is also on shard 1.
I recreate this issue:
- I stopped my running node (validator) on shard 0 (having rewards)
- Reset DB and .dht folder
- Choose a different key that will run on shard 1
- Started the node with: sudo ./node.sh -k 63404ea556c391f46c3b741750cf6d72acdc7ad9377208f55f133b5dded67b42700ae7db37093b0b75b1aa98e8c3978a.key -N staking -z -D -S
- create validator
- ONLY after delegate 307 ones I got bingos (with only 10 was not working)
- got bingos  BUT no rewards

![image](https://user-images.githubusercontent.com/35432495/75375618-be73f880-58ce-11ea-9735-194529dc0992.png)

![image](https://user-images.githubusercontent.com/35432495/75375638-c895f700-58ce-11ea-95c6-4e23ccf49b84.png)

**Comment by Daniel-VDM** [comment]
Confirmed on my end @rlan35 @fxfactorial

**Comment by sophoah** [comment]
issue still present in harmony ```version v5601-master-20191208.0-224-gc6b27393```

**Comment by sophoah** [comment]
issue is fixed now in ```Harmony (C) 2020. harmony, version v5606-v1.3.2-0-g42db637c```

**Comment by BrunoMarshall** [comment]
Checked with the new version v5606-v1.3.2-0-g42db637c and i can collect rewards
![image](https://user-images.githubusercontent.com/35432495/75604402-9657e580-5ad8-11ea-9af9-ece8a7b83760.png)  
![image](https://user-images.githubusercontent.com/35432495/75604414-c30bfd00-5ad8-11ea-8092-8004d971169c.png)
