### ISSUE TITLE
MultiBLS - MK5 testcase doesn't have the expected outcome!

### ISSUE THREAD

**Issue by JB273** [harmony-one/harmony#2431]
While testing MK5 case it doesn't work as expected on OSTN. (will be edited further today)

**To Reproduce**
1. Make sure test MK4 is working correctly, this means we have an elected validator with 2 BLSkeys running
2. Start the MK5 test by shutting down the node.sh process on node2
3. Wait for epoch change
4. Validator goes from `elected` to `not elected` and is not showing rewards building up
5. Node1 is still activily creating rewards (BINGO's)

**Expected behavior**
Validator should stay elected and still be earning rewards, because of node1 still running active

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4

**Comment by sophoah** [comment]
In order to test MK5, I am making sure MK4 is working fine
node 1 runs 1 BLS in shard 0 (with node.sh and -k):  
```
bf3c6ec088cd66fdb540860bd6505b272230164b0510d5f470042d47118d4c8bbe005d28e5de5e489fa22e4ca450c080
```
node 2 run 1 BLS in shard 0 (with node.sh and -k):
```
bf3c6ec088cd66fdb540860bd6505b272230164b0510d5f470042d47118d4c8bbe005d28e5de5e489fa22e4ca450c080
```
Checks that : 
- Both are BINGO-ing without issue
- validator active flag is set as true
- validator is elected

1 min before change of next epoch, i am doing a CTRL+C of node 2

Expectation is that
- validator active flag stays true
- validator stay elected
- reward are only working for node 1 (still running the node via node 1 BINGOs)

however here is the actual result
- validator active flag is set to false --> have to understand why as for sure the validator has signed more than 66% all the blocks in the epoch
- node 1 still BINGO-ing and reward are divided by 2 as expected

node stopped:
``` 
node.sh: ############### Running Harmony Process ###############
Staking mode; node key 06985148242852c659ebabf2415c534a099cf91767639d33da8a38aebe60998a5360c69da55fcc46eaaa470901dc1810 -> shard 0

date^CGot interrupt signal. Gracefully shutting down...
Successfully shut down!
node.sh: received SIGINT
node.sh: terminating update checker (pid 5958)
./node.sh: line 604: kill: (5958) - No such process

root@scw-vigorous-herschel:~# date
Mon Mar  9 15:26:05 UTC 2020
```
```
root@scw-vigorous-herschel:~# tail -f latest/zero*.log | grep BINGO
{"level":"info","port":"9000","ip":"212.47.229.123","blockNum":9290,"epochNum":123,"ViewId":9290,"blockHash":"0x31cce6cb48e05a060541be2027937563ab9a0be10d29bc436cb30d1c09a77248","numTxns":0,"numStakingTxns":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/node/node_handler.go:446","time":"2020-03-09T15:25:52.161462296Z","message":"BINGO !!! Reached Consensus"}
^C
root@scw-vigorous-herschel:~# date && ./hmy -n https://api.s0.os.hmny.io blockchain validator information one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd | grep active
Mon Mar  9 15:25:56 UTC 2020
    "active": true,

date && ./hmy -n https://api.s0.os.hmny.io blockchain validator information one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd | grep active
Mon Mar  9 15:27:12 UTC 2020
    "active": false,
```
so from here if we don't change the active flag to true, the validator will be kick-out from committee

the 2nd node will still BINGO but reward would no longer be earned.

using ```Harmony (C) 2020. harmony, version v5644-master-20191208.0-267-g87963bb7 (jenkins@ 2020-03-06T19:57:09+0000
)```

**Comment by fxfactorial** [comment]
You can still earn rewards if your validator is set to inactive. The moment of important on when the value of the flag matters is at new epoch time, at that block because that's when commitee assignment occurs. 

The field will be changed soon in this PR 

https://github.com/harmony-one/harmony/pull/2396

**Comment by gupadhyaya** [comment]
@JB273 @sophoah can you guys confirm if this issue still exists?

**Comment by sophoah** [comment]
@gupadhyaya in `version v5730-v1.3.5-39-ga429d020` this issue seems to be fixed now. all work as expected. I've checked with @JB273 we are closing this issue
