### ISSUE TITLE
Multiple BLS keys per node

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/harmony#2450]
### Context
A Harmony validator can register with multiple bls keys, however current design requires that validator spin up a node for each of their bls keys to sign and earn reward. Running a node for each of their bls keys incurs substantial cost.

### Proposal
A validator can utilize a single node (or a small set of nodes) to sign for their bls keys. The only constraint is that a node can only sign for multiple bls keys that belong to the same shard. The node that is signing for multiple bls keys of the validator only runs a single consensus and maintains a single blockchain for the shard that validator keys belongs to.

### Precursor
* In Harmony, validators choose to have multiple bls keys to maximize the stakes and rewards, as EPoS discourages large stakes

### Benefits
* Reduces the infrastructure cost for Harmony nodes (~60%)
* Reduces the operational cost for Foundational/External node runners, increase profit

### Drawbacks
* Too many bls keys signing using a single node creates a single point of failure (validator’s risk)
* Reduces network decentralization (less physical nodes, but same amount of keys)
* Easier to dilute median stake, voting power, and reward shares
* Transaction gas needs to take into account of number of bls keys

### Future
A validator can utilize a single node to sign for bls keys that are mapped to different shards. This means that the node needs to maintain multiple shard chains and run multiple consensus.

Please discuss the pros and cons of this new feature here.

**Comment by BrunoMarshall** [comment]
This is really a great feature, I'm currently running a node with 5 bls keys (5 validators) and I'm really impressed. I think that the major driver for me is to avoid the cost of extra instances to run other keys. 
There are some small thing the need to be added, to turn the multi blskeys more user friendly, for example:
- choose automatically the blskeys in the same shard from the folder
- display each bls with the option to input password individually case key.pass not presented on the folder.
- similar to TUI but for multikeys, option to check in one window the node status

**Comment by mindstyle85** [comment]
While this is a great feature for reducing costs for Harmony as well as the validators, I think it is greatly outshined by the fact that it is a step backwards from decentralization and also from network security, since there will be less instances running due to it, which will cause the network to be more susceptible for DDOS and other attacks. So in my opinion cost saving <<<<< decentralization and security.

**Comment by sophoah** [comment]
Nothing really much to add here. That feature is for sure really great to save on network/disk space/number of node instances, it works really well and had it tested with 100 BLS key at once. However, security is real concern here, If my node goes dark this is 100 BLS that goes offline and that is a big risk for the network.

**Comment by zerooneblock** [comment]
In my opinion using multi BLS is a trade off, which in the end has more disadvantages/risks than advantages.
Advantages:
- reducing operational costs;
- easier management of multiple keys in case of no issues; 

Disadvantages: 
- reducing decentralization;
- increasing risks of getting a much higher penalty->in case the physical hardware has any defects or issues. Management of the keys and setup will also take longer compared to single BLS validator, once a problem appears due to many factors: human stress/panic factor during downtime, technical - everything has to be checked multiple times to make sure all the correct keys are there. For a professional validator or staking as a service offerer this single point of failure represents a really large risk and would personally never delegate my tokens to a validator using multi BLS. 
- Having multiple validators running in this mode decreases the overall network security and stability. It is enough to attack one single instance to get access to multiple validators. This would decrease network security. Also in case of large issues with cloud providers like Contabo or Vultr, this could substantially reduce the number of healthy validators assuring network performance and stability. A blockchain network has to be performant, stable and resiliant. Multi BLS represents a big risk for all these components, in my opinion too big to be worth it.

**Comment by BrunoMarshall** [comment]
Maybe off-topic, but what about multi nodes per instance? Each node running in different shard, one key per shard, max 4 keys(validators) in total per instance

**Comment by sophoah** [comment]
@JB273 and I discussed multi-BLS in telegram, here is a summary of the discussion: 
- to avoid centralization via multi-BLS feature, JB suggested to increase gas fee (so 1 BLS is 100% gas, 2nd BLS is 200%, 3rd BLS is300% etc...)
- however since gas are usually low and gas fee are more used to avoid network tx spams I mentioned that the only main solution is to limit the number of BLS per validator in the protocol
- current implementation allows up to 1/3 of external validator (originally 5), in OSTN it means 33 BLS. However in a 100 external validator setup, that means only 25 slots are available for a network of 4 shards.
- we mentioned that there is one corner case that we haven't tested:
  - create validator with 33 BLS
  - make sure that only 25 are earning
  - create another validator whose delegated token would be above our 33, and now only 24 should be earning

**Comment by gupadhyaya** [comment]
Great discussion on the feature. Thanks for your feedbacks.

Restricting multi-bls feature to only Harmony validating nodes is unfair, as some of our stake partners can greatly benefit from this feature. 

To mitigate the centralization concerns, we are planning to impose restriction on:
* the number of bls keys per validator (upper-bound of 1/3 of the total external validating slots) and,
* the number of bls keys per node (upper-bound of 4 keys per node)
We believe this should allow enough flexibility without reducing the decentralization of our network.

Regarding increasing the validator creation gas fee won't be of much help, as our gas fee equivalent dollar amount is still very low. 

Let us know what you guys think about the upper-bound restrictions that will imposed?

**Comment by mindstyle85** [comment]
ok to anyone that doesnt know what the meaning of a node is - a node is an instance running one copy of harmony binary (basically one node.sh)

regarding the imposed restrictions: why not just hard limit it for 4-5 per validator? it will help every staking partner while still not allowing the network to get too centralised and with that less secure

**Comment by JB273** [comment]
The thing with MultiBLS as it is now, it seems to be marketed as a price saving solution! Like @gupadhyaya said, "stake partners can greatly benefit from this feature".
This is exactly where the problem is, my view on this is should be OpenStaking where everyone has a fair change on being a validator, at this moment all is set for company's (or partners) who can afford an own infrastructure to get the most out of it! Let's not be blunt about this, that's how market works... if people can earn easy money they will!
In the current situation it is still possible bigger staking partners will dominate the market, so the protocol will be risking centralization...!?
How are we going to prevent this, if even possible... it's also the job of Harmony to prevent this!
Although from P-OPS pov we like the idea of MultiBLS and we can play with that in a nice way, I still think we must see the bigger picture... Unfortunate all good things will always be used in a bad way by company's which have only profitability as driver and other bad people (internet criminals)!
I would rather see MultiBLS being cut down to 2, but max. 3 per node if we go through with this.
There also should be a BIG cost if some company or user is putting decentralization jeopardy!

**Comment by sophoah** [comment]
@gupadhyaya Could you explain what are the reasons behind using 1/3 of total external validator, my gut feel here is that we are adventuring into some corner cases as described above. For me I would go for either:
- option A : 1/(total number shard + 1)
- option B : 1/(total number of shard)
- Option C: just limit it to the upper limit cap per node
with my preference to go with option C

so let's assume for now a network with 100 nodes and 4 shards (with 25 external per shard) : 
- Option A 
  - with 100 / (4 + 1) = 20 slot available, there would only be 5 slot available for community validator node runner (this is really not a lot)
  - A second partner would have no choice than to beat the first partner if he doesn't want to run into the risk of having 20 of its BLSs not in any of the shard slot
  - and if we add some community nodes that are above all those partner, the number of BLSs out of the shard slot would increase.
==> really need to test carefully
- Option B
  - will mean the partner will use the entire shard for its own usage : all 25 slots taken in the shard
  - let's add a community node runner that stake above the partner, now one BLS from the partner would not earn
==> will need to test that
- option C
  - we'll still have some of those corner cases that will need to be tested
  - however at least there are more rooms for community members and a mix of partners in the same shard without too much major issue
  - this one is great as well, because, Partner don't need to centralize all the wealth into one validator on one shard. It would allow them as well better flexibility if they wanted to swap shard by not putting everything under one validator

Option A and B or your proposal 1/3 is anyway something I don't think anyone would implement in mainnet practically , so let's stick to option C :) if you wanted my personal opinion

Finally. I like the idea of limiting the number of BLS keys per node to avoid centralization, 4 or 5 is reasonable for me and is align with my option C :)

**Comment by zerooneblock** [comment]
@gupadhyaya To me it looks too complicated for a multi BLS functionality. A hard limitation of 3 bls keys per validator would be a first start and let's say an acceptable trade-off.

**Comment by JB273** [comment]
> @gupadhyaya Could you explain what are the reasons behind using 1/3 of total external validator, my gut feel here is that we are adventuring into some corner cases as described above. For me I would go for either:
> 
> * option A : 1/(total number shard + 1)
> * option B : 1/(total number of shard)
> * Option C: just limit it to the upper limit cap per node
>   with my preference to go with option C
> 
> so let's assume for now a network with 100 nodes and 4 shards (with 25 external per shard) :
> 
> * Option A
>   
>   * with 100 / (4 + 1) = 20 slot available, there would only be 5 slot available for community validator node runner (this is really not a lot)
>   * A second partner would have no choice than to beat the first partner if he doesn't want to run into the risk of having 20 of its BLSs not in any of the shard slot
>   * and if we add some community nodes that are above all those partner, the number of BLSs out of the shard slot would increase.
>     ==> really need to test carefully
> * Option B
>   
>   * will mean the partner will use the entire shard for its own usage : all 25 slots taken in the shard
>   * let's add a community node runner that stake above the partner, now one BLS from the partner would not earn
>     ==> will need to test that
> * option C
>   
>   * we'll still have some of those corner cases that will need to be tested
>   * however at least there are more rooms for community members and a mix of partners in the same shard without too much major issue
>   * this one is great as well, because, Partner don't need to centralize all the wealth into one validator on one shard. It would allow them as well better flexibility if they wanted to swap shard by not putting everything under one validator
> 
> Option A and B or your proposal 1/3 is anyway something I don't think anyone would implement in mainnet practically , so let's stick to option C :) if you wanted my personal opinion
> 
> Finally. I like the idea of limiting the number of BLS keys per node to avoid centralization, 4 or 5 is reasonable for me and is align with my option C :)

Would go for a hard limit of only 2 or 3!

**Comment by C10NU7** [comment]
Yoyo !!! How about we keep this feature only for internal nodes ,because i know heavy days are upon us atm and team should reduce the cost as much as posible and let's see first the interest showed by partners and other participants for a period a time after OS is launched and until then we can monitor the behavior in network, thinking more at the design of MKeys ,implement the multiple keys feature ,etc...but first let's keep it this launch as smoothly as posible "for everyone" and in decent terms of release...

**Comment by staking4all** [comment]
The pros and cons have been discussed. 

To summarize the main points are

- Con : Multiple BLS keys creates a bit of centralization, also single point of failure. Also reduces number of seats available for the community
- Pro : Multiple BLS reduced hardware cost

I think the next step is how to manage and reduce risk

To reduce the risk of single point of failure you could make it that the validator can only use multi bls if more than one vps instance exists, force the validator to run two vps instances that each have their own ip address. So for example run 4 bls keys over 2 vps instance, like this if one vps instance fails the other will carry on. Reduces single point of failure

To improve how many seats are available but also ensure all seats are filled when open staking launches, it might be good to start with max cap of 3 or 4 per node! However  make it a known fact that in future versions that this cap will decrease. This allows over time as more validators enter the ecosystem that the bls key cap can decrease to make availability for new entrants. Will also force decentralization more as the network grows

Hope the feedback helps

**Comment by BigCryptoKing** [comment]
I am so glad pretty much everyone feels that multi bls to some extent has more cons than pros! I was really against it for a combination of what you have stated above....network security, node runner security, central, seats avail.  I originally was going to run many servers b/c I didn't know if i was going to be able to figure multi bls out...with a little help I did..and I will be running many servers maxing bls per server...this is what people will do to maximize profits(those holding massive amounts of coins)...this is a numbers game. That is the truth of the matter. I have no problem spending the little extra money/time to set up multi servers to run the desired amount of nodes to reach my goal.  Multi bls would make it a ton easier for me to launch and make money....but I am all for multi server to have multi nodes (network security) Extra time, extra money, but for things that are far more important to network and community that are running nodes/taking  :) <3
