### ISSUE TITLE
staking.harmony.one staking stats & usages from google analytics and ./hmy utility committees (google analytics: unique visitors, staking usage, delegation total)

### ISSUE THREAD

**Issue by NiteeshHarmony** [harmony-one/harmony#2464]
# Overview

staking.harmony.one staking stats & usages from google analytics and ./hmy utility committees (google analytics: unique visitors, staking usage, delegation total)

**Comment by lijiang2087** [comment]
google analytics: unique visitors, staking usage, delegation total

**Comment by john-harmony** [comment]
This is a very vague request it could be better formatted with clearer requirements it appears you are after the following
1. Google Analytics setup -> This can track unique visitors, page hits, etc
2. Staking Usage -> What exactly do we want here, 
3. Delegation Total -> Unsure what we want here

**Comment by ivorytowerdds** [comment]
Progress
====
1. **Already get the unique users**: 
here is the result till now for today: 
https://drive.google.com/open?id=1Pl5Gw_C7hnhen_0Djs5tcv6UlB2vg7zT

2. **Research on google analytics and watched some tutorial** 
From my understanding, google analytics tool is a very good tool for e-commerce company to get the info like acquisition, behavior and conversion by tracking the  # of users visiting the website (acquisition), # of session the user stay for the website(behavior, possible to be a customer), # of clicks on one button (conversion, e.g. click the subscription button). 
- This means Google analytics is just the **right tool to get the new user data**, but **not so applicable to get the staking usage, delegation total**. 
- For **new validators**, an estimate is to use the new user number, since unlike other e-commerce website, a new user will less likely visit our website only after he creates a new validator and come to see that. But the cons are not accurate, we cannot rule out the possibility that people visit randomly. 
- For **delegation transactions**, one way I think of is to get the # of clicks on our `stake` button, but it has potential issue, since you can not get the data of undelegate, and also the implementation needs cooperation from our frontend engineers, to add a javascript inside the code to track the data. I tried to contact Minh but didn't get reply. 
(reference for how we can get the # of clicks using google analytics: https://www.lovesdata.com/blog/google-tag-manager-button-click-tracking) 

3. Instead of using Google analytics, I use **web-scraping** to get our data from 
`https://staking-explorer2-268108.appspot.com/networks/harmony-open-staking/staking_network_info` and
 `https://staking-explorer2-268108.appspot.com/networks/harmony-open-staking/validators_with_page?active=false&page={page}&search=&size={size}&sortOrder=desc&sortProperty=expectedReturns` 
(ps: the parameter `page` and `size` can be modified to get all the data. I got all the validator and delegator data. We can get the total validator numbers and delegator numbers for each validator. I select some important columns and do basic calculation on delegators, the result is like this 
![image](https://user-images.githubusercontent.com/34232522/76656019-ecdb1000-652b-11ea-8b06-d664f440ce86.png)
By running the script every day on fixed time, we can get the new validators.

**Comment by ivorytowerdds** [comment]
Questions 
=====
Tool
-----
After talking to @john-harmony, also thanks to John, I realized we have postman to get all the validator info, and the curl command is the same logic for web scraping. So I think I will use postman or web scraping to get the data. 

Goal
----
As for staking usage and delegation total: from my conversion with @lijiang2087 the goal is to get: 
- one is how many people started a validator
- other is how many people delegated to a validator
- how many delegation transactions happened in a day

For the first one, it's clear. 
For the second one, do we want to get the number of delegator for each validator, if we have a lot of validators later, is it meaningful to get that stats?
Suggest we change to the total delegator number, should it be the new delegators everyday or just total delegators?

For the third one, do we want to get the delegation amount or number of transactions?  The delegation number can be get here. 
```
{'self_stake': 1e+22,
  'total_stake': 1e+22,
  'average_stake': 1e+22,
  'average_stake_by_bls': 1e+22,
  'remainder': 9e+22,
  'voting_power': 0.13513513513513514,
  'signed_blocks': 50,
  'blocks_should_sign': 100,
  'uctDate': '2020-03-13T18:34:15.575Z',
  'index': 18334,
  'address': 'one12mr00g5l9juwt7xk8p88qhs7v77etmtr7awh6m',
  'bls-public-keys': ['6cfbc226ebe374c8b0dffa4ee1ec538fbaaef9fc5857afcdba5fa330bbbaa1cde689080e1f66dc31b333ad85fe7c9f09'],
  'last-epoch-in-committee': 5,
  'min-self-delegation': 1000000000000000000,
  'max-total-delegation': 1e+23,
  'rate': '0.100000000000000000',
  'max-rate': '0.500000000000000000',
  'max-change-rate': '0.100000000000000000',
  'update-height': 214,
  'name': 'E',
  'identity': 'J',
  'website': 'harmony.one',
  'security-contact': 'J',
  'details': 'Shard1Sentry',
  'creation-height': 214,
  'epos-eligibility-status': 'active',
  'delegations': [{'delegator-address': 'one12mr00g5l9juwt7xk8p88qhs7v77etmtr7awh6m',
    'amount': 1e+22,
    'reward': 882150268689828500000,
    'undelegations': []}],
  'availability': {'num-blocks-to-sign': 158, 'num-blocks-signed': 51},
  'active_nodes': 1,
  'active': False,
  'uptime_percentage': 0.3227848101265823}```

For the delegation transaction and creating validator transaction, actually I already did this (more data available can be seen here: https://github.com/harmony-one/harmony-log-analysis/blob/master/notebooks/test_log_analysis/2020_03_10_OSTN.ipynb)
![image](https://user-images.githubusercontent.com/34232522/76657677-a2f42900-652f-11ea-83eb-05748ff54a17.png)

**Comment by ivorytowerdds** [comment]
Update
=====
1. New Users: see https://drive.google.com/open?id=1MOfVejNl0AsSxpWv57S7g1WM7i5fCFne
2. Delegating transactions: refer here: https://github.com/harmony-one/harmony-log-analysis/blob/master/graphs/test_logs/OSTN_03_10/png/shard%200_staking_info_vs_time.png
3. Validator and Delegator info: write a python script to run every 24 hours (10:26 am pst the refreshed OSTN deployed at this time) currently run locally, but if we want to keep the monitor in the future, it should be moved to run on aws. @lijiang2087 
The script result will be like this (using 60 seconds to show the effect), also save a csv file:
![image](https://user-images.githubusercontent.com/34232522/76665524-66cbc300-6545-11ea-9dc1-da566c28e0b5.png)
the csv file will be like this, do we need this?
![image](https://user-images.githubusercontent.com/34232522/76666549-0f7a2280-6546-11ea-94d1-1bbfc2d56ab8.png)
The python script is here: https://github.com/harmony-one/harmony-log-analysis/blob/master/notebooks/staking_dashboard/daily_monitor.py
