### ISSUE TITLE
[Feature] Enable the possibility to delegate to another validator without unstaking 

### ISSUE THREAD

**Issue by Chainode** [harmony-one/harmony#2510]
# Problem/limitation At Hand

At current state there is no option for delegators to quickly move their stake in case they want so. They have to unstake first and stake with another validator afterwards. 
There are many reasons to change the validator as fast as possible without unstaking the ONE tokens:

- validator starts to behave malicious and is in danger of getting slashed;

- validator has problems with uptime and is in danger of getting slashed;

- validator isn't taking care of EPoS consensus rules and loses the seat and the delegator is stucked until it has unstaked and changed the validator;

- user experience and flexibility while doing staking: no need to unstake, wait and then stake again; 

# Proposed Solution

The solution would be to have the staking process at core protocol in 2 steps: stake and delegate. The staking part would mean that a delegator defines how many tokens wants to stake. 
In the delegation part the delegator selects the validator to stake with. This will allow later for a delegator to redelegate to another validator as well as to split the stake among multiple validators, thus supporting decentralization of power even more. 

On the front-end side (staking dashboard) would mean that there will be a button/function to:

- stake, where a certain amount X from the wallet will be defined and locked for staking;

- unstake, where a staked amount X will be released from staking after a certain period of time/epochs;

- redelegate, where a delegator selects another validator to stake with;

# Possible expansion of the solution

Once a delegator has an X ONE amount staked and locked, this amount X can be then delegated to multiple validators, as desired. So the possibility of delegating to multiple validators and changing them as desired is introduced without the need to unstake. Unstaking should actually be used only when the user wants to use the tokens for other purposes than staking. Changing the validator shouldn't require unstaking.

**Comment by mindstyle85** [comment]
I agree with this fully. Like we already discussed a few months ago, it would not be fair that delegators get punished if a validator they delegated to does not get a seat. In that case they stay empty handed and have to wait for 7 epochs to delegate again. The same goes for all the above cases mentioned. I do believe a delegator should have a more flexible abilities here, to at least re-delegate (so no need to return funds to wallet for use).

**Comment by sophoah** [comment]
I really do believe this enhancement would encourage delegator to delegate more. The mentioned issue above is a big downside of the current staking protocol. If implementing staking and delegating function as suggested by @Chainode is a too complex, I am thinking to allow a new feature call re-delegate (really different from undelegation).

Undelegation is when we want to be out of the staking system. Re-delegation is the ability to move your currently delegated token from a validator X to a validator Y.

Another advantage of this solution is to provide flexibility for a delegator to move from one shard to another (because they may think, the other shard can provide them a better APR).

**Comment by OgreAbroad** [comment]
I think that this is an outstanding solution.  It allows delegators to move their stake freely, and keeps the 7 day undelegate in place to discourage traders jumping ship in every market spike.

I feel that this would increase the health of Harmony network considerably.

**Comment by BrunoMarshall** [comment]
nice proposal, like it!

**Comment by rlan35** [comment]
I agree with the user experience impact on this feature. But the implementation of it may not seems as easy. Please read this https://twitter.com/Corbu_Valentin/status/1248037713305100289?s=20

We may add this feature eventually. But it won't be a launch blocker.

**Comment by mindstyle85** [comment]
@rlan35 i dont see it being a problem re: slashing. I think slashing will occur much faster than any delegator will realise, to be able to move tokens away. We can even make it an epoch to re-delegate, just that it doesnt have to wait for 10,5 days (imagine the validator they delegated to gets booted out due to lower bid size, so now this delegator is stuck without earning for a few days)

**Comment by Chainode** [comment]
After doing some experiments with delegation-undelegation-redelegation to the same validator, which worked I had a second thought on this feature. I think we need to analyze its impact also from a financial perspective as it might open the gates for the following scenario:
A staker moves the tokens from one validator to another without any restriction and could impact both its APR and election. I think with the current system and fixed redelegation to the same validator we have more economic stability for validators. I think it would be great to describe and analyze all possible scenarios that can happen if this feature will be implemented and released, so that we avoid a negative impact for validators. 

I still think it's a cool feature but initially I haven't thought at the economic impact for the validator.

**Comment by sophoah** [comment]
@rlan35 i was listening to the community hangout on your answer regarding this feature and the complex logic to verify verify and make sure that we have the logic to trace fund for the last 7 epoch is available.

At first, since I don't expect lots of double slashing happening, could we implement something like, allow re-delegation only if the validator is not currently slashed. and don't add the tracing yet ? Reason being, of this is: 
1) deliver a feature that most delegator are in high demand faster
2) Assuming double slashing detection is immediate, I would say that should be quite safe to just prevent the delegator to change if the validator is currently being slashed. 

I am not sure how a double slash be detected after a re-delegation is done.

**Comment by rlan35** [comment]
@sophoah thanks for the suggestion. We are reevaluating the feasibility of allowing undelegation with shorter lockdown time. Also for token staked on a unelected validator, it's possible that the whole locking time can be avoided.
