### ISSUE TITLE
Consistently getting elected with a tiny amount staked

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/harmony#2525]
**Describe the bug**
Editing the validator and activating it gets it elected to the committee irrespective of the stake or blocks signed.

Case in point:
Validator address: one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl
Effective Stake: 1 $ONE
Epochs signing percentage: 0

**To Reproduce**
Create a shell script with the following code and run it 
`
#!/bin/bash
while true
do
./hmy --node="https://api.s0.os.hmny.io" staking edit-validator-addr one1vfqqagdzz352mtvdl69v0hw953hm993n6v26yl --active true
done
`

**Expected behavior**
This is a validator running on a home-server with 
1) bad uptime 
2) tiny amount staked (1 $ONE)
3) zero blocks signed 
There are other nodes with way better up-time and staked amounts. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29485946/77003567-05f21f80-6977-11ea-9219-026d895e45a2.png)
![image](https://user-images.githubusercontent.com/29485946/77003652-2fab4680-6977-11ea-9ef4-3618572ec75d.png)

**Environment (please complete the following information):**
node.sh: version: v1 20200313.0
Harmony (C) 2020. hmy, version v321-2c589a6 (edgar@harmony.one 2020-03-11T21:21:53-0700)
ubuntu linux 18.04 lts

**Comment by mirrormirage0** [comment]
This issue was also reported by @BrunoMarshall

**Comment by mirrormirage0** [comment]
Stopping the script now , since it affects median stake.

**Comment by BrunoMarshall** [comment]
Another point to refer is that the delegators will look to the explorer, and will see this validator "active" and are deceived to delegate to this "pseudo" validator. we should avoid this.
-If the validator is not running a node **should not be elected**

**Comment by sophoah** [comment]
@BrunoMarshall @mirrormirage0 for me everything work as expected. 

With the recent code upgrade and the epos status as defined here : harmony.one/epos-status, at the time where we set our validator to active, you will be ready to be elected. So during epoch change where the auction will be live, even if you have only 1 ONE or 1mil ONE, the protocol would only look at if you are eligible to be in the committee (auction rules here would applies).  In mainnet I won't be worried because i am sure with multi-BLS, those validator with 1 ONE won't be elected because everyone would want to have a slot and able to earn via their own validator. 

Next, once you are in the committee, this is where the protocol will kick you out (since you are not signing bocks), but before that, the protocol won't know if you are signing blocks or not. How do you identify those validator before hand?

**Comment by mirrormirage0** [comment]
@sophoah , 
I'm trying to understand this better. Out of the 45 validators in OSTN as of now, I have the lowest amount staked 1 $ONE and I am consistently in the committee of 36. Not getting kicked out.
Which makes me wonder, are the rest of the validators performing worse than me (in terms of signing percentage & stake) and hence not getting elected to the committee?

**Comment by mindstyle85** [comment]
no, its the fact that there are 200 seats open, so currently everyone with any stake can get in, but you would be one of the first ones that would get kicked out if all seats would be taken

**Comment by sophoah** [comment]
@mirrormirage0 I think @mindstyle85 answered correctly. there are currently 200 seats and as long as those seats are not being filled up with multi-BLS or new validator, you'll still be eligible and able to run a validator with 1 ONE :)
