### ISSUE TITLE
[mainnet] setup hourly ldb snapshot

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#2998]
To prepare for the worst case of the DB corruption and recovery, we need to set up a sentry node per shard and do an hourly snapshot of the entire harmony DB.

The DB snapshots can be kept in an internal bucket, and we can have a data retention policy of like 2 weeks.

Please use ansible role/playbook to automate the process.

**Comment by LeoHChen** [comment]
Here is some basic script I used to start with,

```bash
#!/bin/bash

NOW=$(date +%F.%T)
SHARD=0
BLOCK=$(curl -s --request POST 'http://127.0.0.1:9500/' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "hmyv2_blockNumber", "params": [], "id": 1}' | jq .result)

mkdir -p snapshots

echo stop: $(date) > snapshots/${NOW}.log
sudo systemctl stop harmony
sleep 1
sync
rclone sync /home/ec2-user/harmony_db_${SHARD} /home/ec2-user/harmony_db_${SHARD}.rsync --transfers 64
sudo systemctl start harmony
echo start: $(date) >> snapshots/${NOW}.log

rclone sync /home/ec2-user/harmony_db_${SHARD}.rsync mainnet:pub.harmony.one/mainnet.min/shard${SHARD}/harmony_db_${SHARD}.${BLOCK}.${NOW} >> snapshots/${NOW}.log 2> snapshots/${NOW}.err

echo done: $(date) >> snapshots/${NOW}.log
```

**Comment by LeoHChen** [comment]
The current snapshot setup is here: https://s3.console.aws.amazon.com/s3/buckets/pub.harmony.one/mainnet.min/?region=us-west-1&tab=overview

**Comment by LeoHChen** [comment]
also, we would like to build a tool to restart using the snapshot, this one can be starting point as well.

https://github.com/harmony-one/experiment-deploy/blob/master/tools/install-db-snapshot.sh

The snapshot restore can also be an ansible role/playbook, so that we can quickly use it to restore the node/shard.

**Comment by Daniel-VDM** [comment]
Due to the reliance on the beacon chain (specifically for crosslinks), I think it's better if we snapshot based on the beacon chain block height instead of time. Since every node has a copy of the beacon chain, we could check for the node's beacon height with `GetLatestChainHeaders` RPC, and if `BEACON_HEIGHT % 450 == 0` we do the snapshot.

**Comment by Daniel-VDM** [comment]
Another question, should we snapshot archival nodes every hour as well?

**Comment by LeoHChen** [comment]
archival node is too huge, once a day would be enough.

**Comment by LeoHChen** [comment]
snapshot based on beacon chain height could be good, but what if the beacon chain sync stuck?  we still need to snapshot the current shard, right?

**Comment by LeoHChen** [comment]
lower the priority now as we have setup a working cronjob on some nodes already.

**Comment by Daniel-VDM** [comment]
Thinking on this more, if we stop all nodes at the same time, we could have beacon chain process 1 block more (and thus 1 batch of crosslinks more) than all aux-shard just based on unlucky timing. 

@rlan35 suggested that we first shutdown and snapshot s0, then do aux-shard afterwards so that we have clean crosslinks (aux shard will just rebroadcast crosslinks).
