### ISSUE TITLE
Pending Transactions stuck in mempool?

### ISSUE THREAD

**Issue by pranavt61** [harmony-one/harmony#3329]
I am currently building up the harmony block explorer. The updated version of the explorer can be found here: http://54.212.182.221:8080/#/

I created a table for "Pending Transactions" and placed it below the "Latest Transactions" table. For some reason, there are transactions that never leave the Pending table.

I am using this RPC command via websockets to populate the table: 
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_pendingTransactions",
    "params": []
}

I am connecting websockets to these nodes:
wss://ws.s0.t.hmny.io
wss://ws.s1.t.hmny.io
wss://ws.s3.t.hmny.io

**Comment by Daniel-VDM** [comment]
It appears that someone's script is constantly sending transactions with invalid nonces.

A quick check with this command show that

**Comment by Daniel-VDM** [comment]
It appears that someone's script is sending invalid transactions.

A check with the following command show that `one13hrrej58t6kn3k24fwuhzudy7x9tayh8p73cq9` has 613 (and climbing) pending transactions.
```bash
curl -s --location --request POST 'https://api.s0.t.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_pendingTransactions",
    "params": []
}' | jq ".result" | grep "one13hrrej58t6kn3k24fwuhzudy7x9tayh8p73cq9" | wc -l 
```

This is a completely legitimate thing to do and won't 'clog' up the pool as each address has a limited number of transactions if the pool limit is reached:
https://github.com/harmony-one/harmony/blob/23fc4486aef8335a7db8708bbd7a14503d535a5d/core/tx_pool.go#L157-L160 
https://github.com/harmony-one/harmony/blob/23fc4486aef8335a7db8708bbd7a14503d535a5d/core/tx_pool.go#L1336-L1345


That said, I noticed some other transactions being stuck in the pool. I suspect that they were added in as non-executable transactions, and thus never tracked for eviction. I will fix this in a PR shortly.

Lastly, It should be made clear that transaction evictions (due to timeout) are based on accounts, not individual transactions. So an account could send an invalid transaction initially, but then always send a valid transaction every block thereafter to keep the initial bad transaction in the pool.
