### ISSUE TITLE
improve external_node.sh

### ISSUE THREAD

**Issue by nicolasburtey** [harmony-one/harmony#355]
- @harmony-ek do we still need all the network related item in the script?
removing them would reduce the background work many non-networking technical people would spend on to understand what all this function are about.

- add more comments, eg: explaining why we are downloading something from ipfs (the public key of the beacon chain)

**Comment by LeoHChen** [comment]
@harmony-ek , can you please help answer the question related to the networking parameters we added in userscript when we launch the node software?  I believe they are mostly used when we were using socket communication.  And since we have moved to libp2p, they may not be needed.

The script is [here](https://github.com/harmony-one/experiment-deploy/blob/master/configs/userdata-soldier-http.sh).

**Comment by nicolasburtey** [comment]
oh the script is now also under /script/ @LeoHChen
