### ISSUE TITLE
new block wasn't proposed after view change

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3575]
**Describe the bug**
For testnet shard0, I brought up my external validator node, and the view change actually worked, with new leader acknowledged by all nodes.  However, no new block was proposed.

I include the log of the new leader after it acknowledged the new leader and sent out the new view message.
[failed_newview.log](https://github.com/harmony-one/harmony/files/6106116/failed_newview.log)

**Comment by rlan35** [comment]
On 03/11/2021, around 11AM PST. Mainnet shard 0 was stuck due to this same issue that happened on testnet where validators failed to process consensus message in time, showing "exceeded consensus message handler deadline". The reason for this issue that that for epoch blocks, the computation needed is increasingly heavy due to the increased number of staking information and the time of processing is exceeding deadline. 

This fix to increase the deadline resolved both the testnet and mainnet issue. This is the PR for the fix: https://github.com/harmony-one/harmony/pull/3576 

Mainnet shard 0 was recovered around 12PM PST the same day by updating the binary of the nodes with the above fix and restarting all nodes together.

Further followup is to dig into the epoch block processing logic to optimize the efficiency of it.
