### ISSUE TITLE
adjust log level during runtime

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#3752]
**Describe the bug**
SetLogVerbosity should be exposed to RPC interface so that we can adjust the log level during the runtime

We used to have it, but I don't remember if it is still working or not.
Please add one RPC interface to make the dynamic log level adjustment working again.

**Comment by LuttyYang** [comment]
@LeoHChen 

I took a look. The `SetLogVerbosity` API already exists and works normally. It is currently subject to the `DebugEnabled` configuration. You can try it by use this command.

```bash
curl -H "Content-Type: application/json" -d '{"method":"hmy_setLogVerbosity","params":[5],"id":1}' http://127.0.0.1:9500
```

Of course, I think this rpc can move to public group, because it has no impact on the overall system, are you prefer to move it out?

Code:
![image](https://user-images.githubusercontent.com/14296262/121911844-aeea1e80-cd62-11eb-82fc-b49b6dfb86c4.png)
![image](https://user-images.githubusercontent.com/14296262/121911927-bb6e7700-cd62-11eb-886b-d6c5c0eac437.png)

**Comment by LeoHChen** [comment]
I think it is okay to move to public group. Thanks for the investigation.

**Comment by LuttyYang** [comment]
@LeoHChen I move it to public group. Please review the code, thanks
