### ISSUE TITLE
[explorer dashboard] account transaction are missing

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#3779]
**Describe the bug**
Transaction are not shown on the explorer

**To Reproduce**
1. submit a tx
2. verify tx is successful
3. go to the explorer dashboard of the sender/receiver account and notice the tx is missing

**Expected behavior**
tx should be seen on a given account

**Screenshots**
N/A

**Environment (please complete the following information):**
NA

**Additional context**
NA

**Comment by sophoah** [comment]
on https://explorer.harmony.one/#/address/one1u5nptqe2yhnvqwrvzxngxnm9h20pnv4mdrumcy we can see the transaction history matches the result of  :  
```
curl -ls --request POST 'https://rpc.s0.t.hmny.io' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "jsonrpc": "2.0",
>     "id": 1,
>     "method": "hmyv2_getTransactionsHistory",
>     "params": [
>         {
>             "address": "one1u5nptqe2yhnvqwrvzxngxnm9h20pnv4mdrumcy",
>             "pageIndex": 0,
>             "pageSize": 2,
>             "fullTx": true,
>             "txType": "ALL",
>             "order": "DSC"
>         }
>     ]
> }' | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "transactions": [
      {
        "blockHash": "0x49c141413af18f7878c525896ea736b37eb497281b0a635af6d0834e8118fc26",
        "blockNumber": 12370695,
        "ethHash": "0x73ddae60eaa75040984053ec5f0e4cc6f6941f12be0b778166668e7b55824b98",
        "from": "one15rgr9rrg42hy23075ztpu9zye2qpqnphvdn3vw",
        "gas": 21000,
        "gasPrice": 10000000000,
        "hash": "0xa44f1e856c1be96e85d47b5d8804aea5b22ddb4cd604ae5b0fb0f9898b0914bc",
        "input": "0x",
        "nonce": 136,
        "r": "0x43c5e0b811cbbb9abc147aa60d1631d0509d234cf29dafc3bb73bb3202284855",
        "s": "0x692925f66d86bc887bfe8370216cab6e7ab0900ee7061a7edb1fcabb822f1862",
        "shardID": 0,
        "timestamp": 1619715369,
        "to": "one1u5nptqe2yhnvqwrvzxngxnm9h20pnv4mdrumcy",
        "toShardID": 0,
        "transactionIndex": 0,
        "v": "0x25",
        "value": 100000000000000
      },
      {
        "blockHash": "0x6909838f73b29094fb82e91a7ec656672aa5a3ec547811d64f57e7df9ad00c36",
        "blockNumber": 12386305,
        "ethHash": "0x395e5bca6acff1a0547878a44865efed5bf7d26b8e9e6f0b607dbb34aea6d9ec",
        "from": "one15rgr9rrg42hy23075ztpu9zye2qpqnphvdn3vw",
        "gas": 21000,
        "gasPrice": 10000000000,
        "hash": "0xf4d02fb479b9171a8f7d7e210d14aca6978aa8db71a7ec357065a2366041e511",
        "input": "0x",
        "nonce": 137,
        "r": "0x45f8fd71d6c90e03e044c63202749bbf786b78a03a38777a85389d0ef88f0138",
        "s": "0x4180c8cdff46fcb89cd9cdb4cf2d2e9e95c9f2fe131a1c32ef5bc946af79803",
        "shardID": 0,
        "timestamp": 1619746691,
        "to": "one1u5nptqe2yhnvqwrvzxngxnm9h20pnv4mdrumcy",
        "toShardID": 0,
        "transactionIndex": 0,
        "v": "0x26",
        "value": 6e+21
      }
    ]
  }
}
```

however check the balance which is actually there was a transfer done on the account which is not being shown

**Comment by sophoah** [comment]
https://explorer.harmony.one/#/tx/0xefb67b845499e05fb45e6632dcec9ed2bf146babea47bb07e168152af253ed4d was done recently and is not shown in the transaction history of https://explorer.harmony.one/#/address/one1u5nptqe2yhnvqwrvzxngxnm9h20pnv4mdrumcy

**Comment by JackyWYX** [comment]
The problem is caused by the fact that the explorer db cannot keep up with 2s per block. With the large amount of spamming transactions at shard 0 mainnet, the unscalable nature of the current explorer DB schema makes the explorer very hard to catch up - each block need to write ~500MB db data and take about 30~40s to finish. 

Thus I proposed this PR fix (https://github.com/harmony-one/harmony/pull/3775/files), which is to adding a caching mechanism before writing data to explorer db. 

After the fix, the expected behavior is that the explorer db will catchup, but slowly. There can be still transactions missing during the catchup, but eventually all transactions should be fetched. On the other side, there is going to be at most 90s delay (on mainnet) for the latest transactions to be available from explorer RPC endpoints. On testnet with smaller account history to be committed to DB, the delay is almost neglectable.

**Comment by sophoah** [comment]
I am closing this issue since #3775 seems to have fix the issue
