### ISSUE TITLE
shard0 upgrade fail for  upgrading 2023.4.2 -> 2024.1.0 but shard1 ok (could not bootstrap consensus)

### ISSUE THREAD

**Issue by jun0tpyrc** [harmony-one/harmony#4697]
**Describe the bug**

**To Reproduce**
```
could not bootstrap consensuscontext deadline exceeded
```
shard1 is fine , shard0 seems problematic

both run with
```
--network=mainnet --config=/opt/conf/harmony.conf --run=explorer --run.shard=0 --datadir=/opt/data/ --rpc.ratelimiter=false --http.ip=0.0.0.0 --ws.ip=0.0.0.0
```
(diff in shard=0 or 1 param only)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by jun0tpyrc** [comment]
custom config:

traceenable=true
  nostaking=true
nodetype=explorer

empty localaccountsfile



(falling back to 2023.4.2 and configversion 2.5.7  it's working)

**Comment by sophoah** [comment]
hey it's a known issue and is actually random because of an instability of the mainnet bootnode.

please upgrade to v2024.1.0 and restart your node every 3-5 min if you keep having peer issue. User have been reported it should work in a time frame between 2 and 30 min after the first restart

Let me know if you have further issue

**Comment by jun0tpyrc** [comment]
verified working as said
