### ISSUE TITLE
post analysis script to find errors in logs

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#632]
## Summary

We need a script to analyze the log files to report errors found during the benchmark test.

## Current Design

We only check the number of consensus / tps.

## Problems

We sometimes missed the opportunity to check SIGSEGV fault or out of memory errors etc.

## Proposal

The post analysis script should integrate/absorb the cal_tps.sh script and do more.

* check SIGSEGV in solider*.log, this is crash, should report the panic.
* check size of validator*.log, found the number of significant smaller log files.  those are abnormal interrupt of the node, usually comes with SIGSEGV fault in solider.log
* absorb the cal_tps.sh script
* runtime error, out of memory etc.

**Comment by andywuexan** [comment]
[1] **About SIGSEGV**
Segmentation Fault (SIGSEGV) is caused when you try to access any invalid memory location.

Now, in your program it can happen due to various reasons.

You are accessing array elements out of bounds.
You are accessing any pointer that is not initialized.
A recursive function with no base case, where it calls itself again and again hence filling up the stack space. It is called Stack Overflow.

[2] Need to define the size for "significant smaller". What is the average size for a regular validate log file. How to find the pattern for this type of abnormal logs? What infomation/value we can extract from them? And how to report them?

[3] Need to fully understand cal_tps.sh script. 

[4] Runtime error? Out of memory? Further research needed.

**Comment by LeoHChen** [comment]
yes, we know the SIGSEGV, the request is to find this error message in the log file.  NO need to do any debug or triage.

**Comment by LeoHChen** [comment]
Related Issue: https://github.com/harmony-one/harmony/issues/565

**Comment by AndyBoWu** [comment]
Progress:
* We have a Python application integrated with AWS Athena to catch `panic` type ERROR in the logs. This feature has been working in the past 2 weeks. All good.
* Got a request from LC to catch all `fatal ERROR` in the logs, WIP

**Comment by AndyBoWu** [comment]
@LeoHChen Feel free to change the assignee of this issue to me. Thx.

**Comment by LeoHChen** [comment]
I can't directly assign the issue to you right now.  Please just work on it.

**Comment by AndyBoWu** [comment]
Understand.

Submitted my code to my repo, and created a PR, asking for boys for review. We will test it out tonight if the new version of the Python script has been integrated in Jenkins. Will keep you updated.

**Comment by AndyBoWu** [comment]
Hi @LeoHChen,

I think we can close this ticket. The python application is working properly as we expected on the Jenkins server. 

Best,
Andy

**Comment by LeoHChen** [comment]
sure.  thanks for the work!
